### PR TITLE
added type property for catalogs and collections

### PR DESCRIPTION
**Pull request by volaya**
**Related Issue(s):** #
 https://github.com/radiantearth/stac-spec/pull/971

**Description:**
Adds tpe property for catalogs and collections

**PR Checklist:**

- [x] Code is formatted (run `scripts/format`)
- [x] Tests pass (run `scripts/test`)
- [x] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/develop/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by volaya** [comment]
Before merging this, one thing to consider:

Pystac uses the 'extent' property to identify collections (see https://github.com/stac-utils/pystac/blob/develop/pystac/serialization/identify.py#L273). That should be changed to now use the type property, but doing so breaks a large number of tests, mainly because sample json files in tests do not have the type property. Those files should be updated, but before working on that, I would like a second opinion about it, to know if it is worth or not. For what I understand, the type property is now mandatory, so sample test catalogs and collections should have it.

**Comment by matthewhanson** [comment]
@volaya That's correct, this is a required property now, and Pystac should be updated to use the type to identify Collections.  I think all the tests should be updated as well.  I think I'd combine the identify changes and example changes into this PR.

**Comment by lossyrob** [comment]
The identify functionality identifies older version of STAC as well, so we don't want to get rid of that. It can start with a check for the property `type` and make decisions based on that, but if something is pre-1.0.0-RC1, it will need to fall back to it's current logic.

The STAC objects that should be updated are the main test data, but all the `examples` test data that are for a specific version shouldn't be changed - those test PySTAC's ability to migrate older versions to new STAC. 
r

**Comment by volaya** [comment]
I added a new commit with changes to the identify function, which now uses the approach suggested by @lossyrob (first try to identify based on the type property, and if that's not possible, use the previous approach).

This also fixes a problem not mentioned in https://github.com/stac-utils/pystac/pull/289 With that PR, Collections can now have assets, and the identify method uses the presence of the 'assets' property to identify Item objects, which will no longer be a valid strategy. No need to change anything in that PR if this one is merged.

**Review by lossyrob — APPROVED** [review]

**Pull request merged**
