### PR TITLE
Implement SAR extension.  #33

### PR DESCRIPTION
**Pull request by schwehr**
I'm new to type hints, so they aren't totally perfect.  The `classmethod`s are likely incorrect.  It would be great to get help to make them be correct or we can drop them. Type hints tested with pytype.

It seems like there should be a subset of `sar` available for collections.  e.g. this, which is definitely not correct.

- https://earthengine-stac.storage.googleapis.com/catalog/COPERNICUS_S1_GRD.json
- https://console.cloud.google.com/storage/browser/_details/earthengine-stac/catalog/COPERNICUS_S1_GRD.json

### CODE REVIEW

**Comment by lossyrob** [comment]
There is a TODO for documentation, but a review request. Is this still in draft state?

**Comment by schwehr** [comment]
Yes, still a draft.  I was hoping you'd take a look at the non-doc part.

But hold off on that and I'll give it another look over myself and add the docs.

Sorry I'm having so much trouble with the github workflow.  The tooling feels very different than the reviews I do internally at Google.

**Comment by lossyrob** [comment]
Gotcha - no worries. I just wasn't sure the state of things. If there's something particular you'd like me to take a look at, happy to, otherwise I think it'll shorten the review cycles if the review can happen all at once when the PR is out of draft phase.

**Review by lossyrob — APPROVED** [review]
Looks great, and good to merge. Few things:

- I added a commit to put the API docs in
- I created #230 to track making our usage of optional properties being set as None, and how that affects the `apply` method.
- I created #231 to track making our usage of Enums consistent. You're using enums here, but they are not used in throughout the rest of the library. I think that's good for now, but we want to eventually be consistent on our usage. If you have opinions about that, please comment in the issue!

**Pull request merged**
