### PR TITLE
Cancel running jobs on github actions

### PR DESCRIPTION
**Pull request by jsignell**
**Description:**
This is a minor workflow improvement where github actions are automatically cancelled if you push another commit to the branch. It can help with speeding up CI runs.

Example: https://github.com/jsignell/pystac/actions/runs/4186696525

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Review by gadomski — CHANGES_REQUESTED** [review]
TIL! Do we need to do https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value, since we run CI on `push` and `merge_group`?

**Comment by jsignell** [comment]
Hmm I've never seen merge_group before but my general sense is it doesn't hurt if the cancel fails. The issue is if it's overly aggressive I guess. Let me read up a bit.

**Comment by gadomski** [comment]
> Hmm I've never seen merge_group before but my general sense is it doesn't hurt if the cancel fails. The issue is if it's overly aggressive I guess. Let me read up a bit.

I just added `merge_group` in e4ff60d698efb8c4f69511e521d9dd4c0c1bbe86 because I wanted to try out [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

**Comment by jsignell** [comment]
I think this will work fine as is with merge groups. The `merge_group` actions seem to have their own branches. This is kind of explained in the [github docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-other-ci-providers) and you can see it in action in this logs from this CI run: https://github.com/stac-utils/pystac/actions/runs/4186900099/jobs/7256027421#step:2:466

**Comment by gadomski** [comment]
Sounds good, and if it breaks we can always fix later!

**Review by gadomski — APPROVED** [review]

**Pull request merged**
