### PR TITLE
Changes to main for v1.2.0 release

### PR DESCRIPTION
**Pull request by duckontheweb**
**Description:**

Updates to package version and CHANGELOG for v1.2.0 release.

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

TODO:

- [x] Rebase on master after merging #647, #658, #659, and #654

### CODE REVIEW

**Comment by duckontheweb** [comment]
We may want to wait until #654 has been merged and incorporate that into this release as well.

**Comment by duckontheweb** [comment]
@lossyrob I've rebased this to include the latest merges, so this should be ready for review.

**Comment by lossyrob** [comment]
@duckontheweb do you think we should try to address https://github.com/stac-utils/pystac/issues/546#issuecomment-966730630 in this release? I'm looking at the code right now and may have a fix tonight, if so I'll make a PR.

**Comment by duckontheweb** [comment]
> @duckontheweb do you think we should try to address [#546 (comment)](https://github.com/stac-utils/pystac/issues/546#issuecomment-966730630) in this release? I'm looking at the code right now and may have a fix tonight, if so I'll make a PR.

Yeah, it's probably worth trying to get a fix for that in. I can take a look tomorrow and see what that would take.

**Comment by duckontheweb** [comment]
@lossyrob This has been rebased onto `main` after merging changes from #663. Ready for review.

**Review by lossyrob — APPROVED** [review]

**Pull request merged**
