### PR TITLE
Xarray Assets Extension class

### PR DESCRIPTION
**Pull request by jsignell**
**Related Issue(s):**

- #846 

**Description:**

EDIT: I removed the `open` method, so this is just a regular extension class now.

This PR implements an extension class for xarray-assets extension with a special `open` method for extended pystac.Assets as described in https://github.com/stac-utils/pystac/issues/846#issuecomment-1587441466

```python
import pystac
from pystac.extensions.xarray_assets import XarrayAssetsExtension

daymet_collection = pystac.Collection.from_file(
    "https://planetarycomputer.microsoft.com/api/stac/v1/collections/daymet-daily-hi"
)
daymet_asset = daymet_collection.assets["zarr-abfs"]
xr_ext = XarrayAssetsExtension.ext(daymet_asset, add_if_missing=True)
xr_ext.open()
```
**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by jsignell** [comment]
Not super ergonomic with the current extension access system, but I'm optimistic that the extension API can be revamped a la #1051 without a substantial rewrite of the classes.

**Review by gadomski — CHANGES_REQUESTED** [review]
Couple high level questions:

- Did you consider adding **xpystac** as a optional dependency (ala **orjson**)?
- How do you see this model working for "containers" that aren't tied to a specific extension? E.g. @TomAugspurger's proposed `to_geopandas` for an `ItemCollection`?
- I think this deserves more than just API docs, e.g. updating how-to-read-data-from-stac.ipynb to use the new extension interface?

**Comment by jsignell** [comment]
>     * Did you consider adding **xpystac** as a optional dependency (ala **orjson**)?

I guess that's a good idea in case we need to pin it later on?

>     * How do you see this model working for "containers" that aren't tied to a specific extension? E.g. @TomAugspurger's proposed `to_geopandas` for an `ItemCollection`?

Because ItemCollections can't have extensions or because there would be no need for a geopandas extension? I was kind of thinking the table extension could be the geopandas extension. I guess alternatively there could be a generic reader extension but that might be too far of a stretch from what extensions are meant to be.

>     * I think this deserves more than just API docs, e.g. updating how-to-read-data-from-stac.ipynb to use the new extension interface?

Yeah definitely. I wasn't sure if people would like this idea, so I didn't bother with that yet.

**Comment by gadomski** [comment]
> I guess that's a good idea in case we need to pin it later on?

Yeah, and it makes it clearer that there's **pystac** functionality that uses **xpystac**, instead of just tests.

> ItemCollections can't have extensions

Yup, this.

> I was kind of thinking the table extension could be the geopandas extension.

But theoretically you could want to make a dataframe out of something that doesn't have the table extension in its `stac_extensions` list, correct?

> Yeah definitely. I wasn't sure if people would like this idea, so I didn't bother with that yet.

👍🏼

**Comment by jsignell** [comment]
> But theoretically you could want to make a dataframe out of something that doesn't have the table extension in its `stac_extensions` list, correct?

Yeah but couldn't you just add the table extension in that case?

**Comment by gadomski** [comment]
> Yeah but couldn't you just add the table extension in that case?

If you don't _need_ the table extension to put the STAC stuff into a data frame, IMO you shouldn't have to add the table extension. Otherwise, I could see a scenario where someone loads some STAC, adds the table extension to do some data frame work, then has to strip the table extension back out again before saving the STAC somewhere else -- feels hackey.

**Review by gadomski — APPROVED** [review]

**Pull request merged**
