### PR TITLE
Bump projection extension to v1.1.0

### PR DESCRIPTION
**Pull request by tschaub**
**Related Issue(s):** #

https://github.com/stac-extensions/projection/pull/17

**Description:**

This updates the projection extension to use v1.1.0.

**PR Checklist:**

- [X] Code is formatted (run `pre-commit run --all-files`)
- [X] Tests pass (run `scripts/test`)
- [ ] Documentation has been updated to reflect changes, if applicable
- [X] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Review by gadomski — COMMENTED** [review]
Do we need the projection v1.1.0 schema in the test data files?

**Comment by tschaub** [comment]
@gadomski - Let me know if you think we should add more tests to explicitly cover v1.0 vs v1.1 changes.  The one added example covers the optional `proj:epsg` property at the item level.  I also didn't update notebooks or other examples that use the projection schema URL.  Happy to make additional changes.

**Comment by tschaub** [comment]
> Do we need the projection v1.1.0 schema in the test data files?

I only guessed that local files might be used instead of making network requests when validating.  But I didn't confirm.  I'll remove it and see how it works.

**Comment by tschaub** [comment]
> I only guessed that local files might be used instead of making network requests when validating. But I didn't confirm. I'll remove it and see how it works.

@gadomski - Looks like tests pass without the schema file.  Latest commit omits it.

**Review by gadomski — APPROVED** [review]
LGTM. @tschaub I just went ahead and made the doc+examples update since I was in the code -- I added a note to `docs/contributing.rst` about those changes. Do you mind taking a look at those, and then we should be good to ?

**Review by tschaub — COMMENTED** [review]
Looks good, @gadomski.  Thanks for updating the docs and notebook.  It looks like there are some pretty significant (unrelated) changes in [the notebook](https://github.com/stac-utils/pystac/blob/d3b5e88d5a93f4da9d040999b97b8cef65478125/docs/quickstart.ipynb). Assuming that might just be because it hasn't been updated / run in a while.

**Comment by gadomski** [comment]
> It looks like there are some pretty significant (unrelated) changes in [the notebook](https://github.com/stac-utils/pystac/blob/d3b5e88d5a93f4da9d040999b97b8cef65478125/docs/quickstart.ipynb). Assuming that might just be because it hasn't been updated / run in a while.

Yup, the biggest change is adding the HTML output (enabled by #743), but I figured it wasn't worth doing a new PR just w/ that update. Thanks for checking.

**Pull request merged**
