### PR TITLE
update raster extension to v1.1.0

### PR DESCRIPTION
**Pull request by pjhartzell**
**Related Issue(s):** #789 

**Description:**

Makes "nan", "inf", and "-inf" valid values for the `nodata` property in `raster:bands`.

- update schema uri
- align the `nodata` type with the updated schema, which allows for numeric and "nan", "inf", and "-inf" strings.
- update tests and test data. For the test data, the `raster:bands` object added to the `B09` asset is from the sentinel example in the Raster Extension repo.

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by pjhartzell** [comment]
Thanks @gadomski for pointing me at #448. Beyond the relevant discussion on how to handle extension updates in the future, it looks like an extension hook should be added to this PR to conform to the current method of handling extension version updates.

**Comment by pjhartzell** [comment]
In this case, the only change between v1.0.0 and v1.1.0 is the allowance of certain strings for the `nodata` value. So updating STAC from v1.0.0 to v1.1.0 only needs the schema URI in the `extensions_list` to change from v1.0.0 to v1.1.0. 

However, [the `migrate` method is only called](https://github.com/stac-utils/pystac/blob/1261e6058e8e9137d5c7c7f16e0d18e888a6d9cf/pystac/extensions/hooks.py#L50) when `stac_version` differs from the current value. So adding an extension hook only migrates the URI if the imported STAC is <1.0.0.

**Review by duckontheweb — APPROVED** [review]
@pjhartzell Thanks so much for working on this, these changes all look good to me. Your comment on the migration only needing to update the schema URI is right on, so I think this is ready to be converted from Draft to PR and merged.

**Comment by duckontheweb** [comment]
@pjhartzell Any objection to me converting this from a Draft?

**Pull request merged**
