### PR TITLE
Rich, HTML representations for Jupyter Notebook

### PR DESCRIPTION
**Pull request by moradology**
**Related Issue(s):** #508

**Description:**

This PR is intended to provide useful HTML representations of some core STAC objects as well as a structure appropriate to adding more such representations. These are primarily used within Jupyter notebooks, but could in principle find use elsewhere.

image

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/develop/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by moradology** [comment]
In the above screenshot, `detail`/`summary` pairs don't appear to be rendering with arrows on their left (as expected). I'm not sure if this is a quirk of my particular installation, but would be interested if anyone has ideas

**Review by duckontheweb — COMMENTED** [review]
Thanks for working on this @moradology , I like the idea of having these rich representations for contexts like Jupyter.

My biggest concern with this approach is adding `jinja2` as a dependency. PySTAC has been extremely careful about not adding non-essential dependencies (see [this comment](https://github.com/stac-utils/pystac/issues/331#issuecomment-867671808) from @lossyrob that gives some good rationale for this), and since `jinja2` is only being added to support a narrow set of features I don't feel that it's worth breaking that tradition.

I'm wondering if this kind of functionality would be better in a separate library (e.g. `pystac-jupyter`, `pystac-html`, etc.) that could provide more specific support in these environments. If we do want it in PySTAC, I think we should try to accomplish this through a combination of factory functions and f-strings instead of adding a new dependency.

**Comment by moradology** [comment]
After writing this, reading your comment and a very brief discussion with @lossyrob, I'm inclined to agree that adding 1/4th more dependencies(!) is probably not wise. I'm not a huge fan of the f-string approach as it stands to add some clutter to already rather large classes and jinja templates are awfully convenient by comparison. Ironically, the f-string approach has fewer downsides within an external project focused on ergonomics inside the Jupyter context. My vote for preserving this kind of functionality - and I do think it is valuable for those who like to develop and to produce learning materials with Jupyter - would be to extend the primary `pystac` classes as necessary from inside an external project like `pystac-jupyter`, as you mentioned.

**Comment by lossyrob** [comment]
I'd agree that creating a `pystac-jupyter` package is the best route, though a bit heavier of a lift. 

Noting that @mmcfarland pointed to these docs previously, which allows you to set custom formatters for types and would probably be useful here https://ipython.readthedocs.io/en/stable/config/integrating.html#formatters-for-third-party-types

**Comment by duckontheweb** [comment]
@moradology Are you okay with me closing this PR since it sounds like this will be implemented as a separate library?

**Comment by moradology** [comment]
Very

**Pull request closed without merging**
