### PR TITLE
Update Landsat tutorial

### LINKED ISSUE #665: Documentation issues - Quickstart gives errors, and tutorial use of .ext fails
I've been trying to get familiar with PySTAC recently, and have found a number of issues with the documentation.

**Quickstart**
Running the code in the quickstart guide at https://pystac.readthedocs.io/en/1.0/quickstart.html gives a number of errors. For example, the first code block runs `from pystac import STAC_IO`, which fails as it should be `from pystac import StacIO`. A bit further down, the call to `cat.get_children()` fails with a `TypeError: list indices must be integers or slices, not str` (I couldn't work out how to fix this). I suspect there may be other issues too.

**Tutorials**
In the _Creating a Landsat STAC_ tutorial (https://pystac.readthedocs.io/en/1.0/tutorials/creating-a-landsat-stac.html#Adding-the-EO-extension), it tells you to run `item.ext.enable('eo')` but this fails, saying that the `ext` attribute doesn't exist. After asking this question on the STAC Gitter chat, I was told to follow the instructions [here](https://github.com/stac-utils/pystac/blob/main/docs/concepts.rst#adding-an-extension), which worked.

(As an aside, I'd be interested as to why the `.ext` accessor was removed, as it seems to be a nicer way of adding extensions)

### PR DESCRIPTION
**Pull request by duckontheweb**
**Related Issue(s):**

- Closes #665

**Description:**

Updates the Landsat tutorial to be up-to-date with the current extensions and StacIO APIs.

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by duckontheweb** [comment]
cc: @robintw

**Review by gadomski — CHANGES_REQUESTED** [review]
So it's not touched by this PR right now, but there's some typing issues, e.g. in the "Set the providers" block:

Screen Shot 2022-01-14 at 8 35 22 AM

Probably worth cleaning those up as well since we're hitting this file? Alternately, is there an equivalent Python typing way to do Rust's `Into`/`From`, since `ProviderRole` is trivially convertable to/from a string?

**Comment by duckontheweb** [comment]
> So it's not touched by this PR right now, but there's some typing issues, e.g. in the "Set the providers" block:
> 
> Screen Shot 2022-01-14 at 8 35 22 AM
> 
> Probably worth cleaning those up as well since we're hitting this file? Alternately, is there an equivalent Python typing way to do Rust's `Into`/`From`, since `ProviderRole` is trivially convertable to/from a string?

@gadomski I fixed the type hinting in 7822724261edb0d04dd5ab15891f1a1e1f215b04 and checked it using `nbqa mypy` (only for this tutorial). I ended up adding type hints to the functions as well as a `TypedDict` to describe the `scene` dictionaries that are used throughout the tutorial in order to satisfy the type checker and hopeful make things more clear. Let me know if you think all of those changes are worthwhile.

As a side note, we may want to add some `nbqa` checks to our tutorials as part of our test suite to catch these issues across the tutorials.

**Review by gadomski — APPROVED** [review]
Thanks, LGTM. This is one of those cases where type-checking can get in the way a little bit, but I think making sure that the notebooks match the "corrent" way of using the API will save end users headaches down the road.

👍🏽 to adding `nbqa` to CI.

**Review by lossyrob — APPROVED** [review]

**Pull request merged**
