### PR TITLE
Reformat docs and move to PyData sphinx theme

### LINKED ISSUE #635: Update sphinx theme
[bikeshedding warning]

Are people attached to the current sphinx theme? I find it a bit hard to read, especially the [API docs](https://pystac.readthedocs.io/en/latest/api.html).

https://sphinx-themes.org/#themes has a nice gallery of themes to choose from. I would recommend one of [Furo](https://sphinx-themes.org/sample-sites/furo/) or the [PyData](https://sphinx-themes.org/sample-sites/pydata-sphinx-theme/) themes.

### PR DESCRIPTION
**Pull request by duckontheweb**
**Related Issue(s):**

- Closes #635

**Description:**

This changes the Sphinx theme for our docs from `alabaster` to the [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html) as suggested in #635. Additionally, it makes some changes to the layout and structure of the docs to (hopefully) make them a bit more user-friendly, especially for newcomers. The layout changes were based heavily on the [Bokeh documentation](https://docs.bokeh.org/en/latest/). Those docs are one of the examples for the PyData Sphinx Theme, and to my eye they provide a really clear landing page that helps direct different audiences to the right place in the docs.

I had also always found the API docs to be hard to navigate, especially as the codebase grew larger. I reworked those docs so that the API Reference has a landing page with cards organized by topics (either related to STAC or PySTAC) and a table of contents organized by module.

~I am opening as a Draft while I get the docs to build on Sphinx as an example, and would love to get some feedback on the theme change, the high-level changes to the structure, and the API Reference changes. Updating some of the tutorials that are still out of date (e.g. #602) will be covered in separate PRs.~

Preview of the new docs is available at https://pystac--687.org.readthedocs.build/en/687/.

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Review by gadomski — APPROVED** [review]

**Comment by duckontheweb** [comment]
@KennSmithDS @alexgleith @robintw @yeelauren You all have raised documentation-related issues in the past, so I thought I'd bring this to your attention. Let me know if any of you have any feedback on the new format/theme. Thanks!

**Comment by KennSmithDS** [comment]
@duckontheweb overall I love the changes so far, the theme is very clean and a lot easier to find the information I'm looking for. Here are some bulleted thoughts:
- Bokeh inspired boostrap theme is way more visually appealing then the old look and feel which kinda hurt my eyes
- Navigating and searching for content has dramatically improved, especially the side panel when browsing API reference
- The code snippets (especially for tutorials) are significantly easier on the eyes to read through example code and spot dependencies
- SUGGESTION: might want to put the STAC logo on the left-most side of the top navbar?

**Comment by duckontheweb** [comment]
> * SUGGESTION: might want to put the STAC logo on the left-most side of the top navbar?

Yes, good idea. I considered doing this and then wasn't sure if I should use the STAC logo or if there was another one that was more specific to PySTAC. @lossyrob @cholmes Do you know if we have any PySTAC-specific logos?

**Comment by lossyrob** [comment]
There's no specific PySTAC logo - I once made one that was just the STAC logo but with the globe replaced by the Python logo. I'm not actually sure this is copacetic wrt the Python logo usage rules. I think adding the general STAC logo would be appropriate.

**Review by lossyrob — APPROVED** [review]

**Comment by duckontheweb** [comment]
Added the STAC logo in 65491b6c3aac7aa6128e25773f101ff0c15ab310. I'll plan on merging this today unless there is any last-minute feedback.

**Comment by alexgleith** [comment]
Looks great. Clean and pretty. Nice work!

**Review by alexgleith — APPROVED** [review]

**Pull request merged**
