### PR TITLE
Add convenience method for accessing pystac_client

### LINKED ISSUE #1334: Namespace the client so we do `from pystac.client import Client`
This is a pedantic nice-to-have!

I would love to be able to get the client like `from pystac.client import Client` rather than `from pystac_client import Client`.

It's a little thing, but it would make me happy!

### PR DESCRIPTION
**Pull request by jsignell**
**Related Issue(s):**

- Closes #1334 

**Description:**

```python
from pystac.client import Client
```

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Comment by jsignell** [comment]
I can either ignore this file in coverage or I can try to figure out a test for the the case where pystac_client is not importable.

**Review by gadomski — CHANGES_REQUESTED** [review]
I'm not to stressed about coverage, but I do think some sort of CI check to make sure we work with and without **pystac-client** installed would be good ... this would be an easy thing to break inadvertently. Also, can you add a quick docs section describing how to use the import? 🙇🏼

**Comment by jsignell** [comment]
All right! I ended up ignoring mypy. Mypy passes if pystac_client is installed, but it didn't seem worth it to try to mock out a stub or something. Another option I suppose would be to add pystac_client as a test requirement, but that might not be desirable.

**Comment by jsignell** [comment]
I just added a smidge of docs:

Screenshot from 2024-08-06 11-26-12

**Review by gadomski — APPROVED** [review]

**Comment by alexgleith** [comment]
Love it! Thank you 🙏

**Pull request merged**
