### PR TITLE
Extension/Table - Added extension

### PR DESCRIPTION
**Pull request by thomafred**
**Related Issue(s):** #

**Description:**
Added support for the Table-extension by @TomAugspurger:

https://github.com/stac-extensions/table

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [ ] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

### CODE REVIEW

**Review by duckontheweb — APPROVED** [review]
Thanks @thomafred, this looks good.

For some reason the coverage is dropping in `catalog.py`, `test_catalog.py`, and `datacube.py`, but I can't see any reason why this PR would be causing that. I'm going to try rebasing onto master to see if that solves the problem, but I don't think we should hold up this PR on account of that.

**Comment by duckontheweb** [comment]
Actually, @thomafred it looks like I don't have permission to push to this repo. Would you mind rebasing this and pushing the changes?

**Comment by thomafred** [comment]
@duckontheweb I have rebased with main and pushed :)

**Review by duckontheweb — APPROVED** [review]
Thanks @thomafred. Looks good to me!

**Pull request merged**
